### PR TITLE
Create voc_label.py

### PR DESCRIPTION
**Pull request by tianfengyijiu**
Transform VOC annotations to label txt.

### CODE REVIEW

**Comment by wizyoung** [comment]
thanks for your contribution. I will check the code when I'm available.

**Comment by linusk** [comment]
@tianfengyijiu First of all thanks for creating this script. I tried to use it and found a couple of issues.

1. The generated file does not have a line number as needed by this project.
2. train.txt and val.txt are written twice, once for 2007 and once for 2012. And because you open the file as "w", it will be over-written.

I modified your file and have a copy here.

https://github.com/linusk/YOLOv3_TensorFlow/tree/master/data/VOC

**Comment by wizyoung** [comment]
This repo is intended to help users to train yolo on their own dataset. Since so many people use the labelimg to get the xml format annotations, I'll add the transform script to the repo myself.

**Comment by wizyoung** [comment]
added: https://github.com/wizyoung/YOLOv3_TensorFlow/blob/master/misc/parse_voc_xml.py

**Pull request closed without merging**
